[phases.setup]
nixPkgs = ["python310", "postgresql", "gdal", "geos", "proj", "binutils", "gcc", "zlib"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = [". /opt/venv/bin/activate && chmod +x build.sh && ./build.sh"]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn maktab_project.wsgi:application --bind 0.0.0.0:$PORT"
